# Site wide configuration

title:            André Werlang
locale:           pt_BR
url:              http://blog.werlangtecnologia.com.br


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: André Werlang
  avatar: bio-photo.jpg
  bio: "throw ProgrammerNotFound();"
  email: 
  disqus-shortname: werlangtecnologia
  twitter: awerlang
  facebook: #username
  google:
    plus: #username
    analytics: 63176420
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: awerlang
  stackoverflow: 592792/werlang
  linkedin: awerlang
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
